services:
  - type: web
    name: your-highness-chat
    env: node
    plan: free
    buildCommand: npm install && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        fromDatabase:
          name: your-highness-db
          property: connectionString
    healthCheckPath: /
    
databases:
  - name: your-highness-db
    databaseName: your_highness
    user: your_highness_user
    plan: free